kindOfOrganisation(motorist).
kindOfProduct(aircraft).
headOfficeInEU(_).
weight(_).
standardPart(_).
mainResponsabilities(_).
typeCertificate(no).
requestModification(no).
nextTarget(designApproval).
requestModificationOrNewProgram(_).
privilegeFromEASA(_).
operationalConditionsMightBeRestricted(_).
